import React from 'react';
import ReactDOM from 'react-dom';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import injectTapEventPlugin from 'react-tap-event-plugin';
import configureStore from 'app/redux/store/immutableStore';
import Root from '../containers/Root';
import Stories from '../containers/Stories';
import { getFromLocalStorage } from 'app/lib/storage';

// Needed for onTouchTap
// http://stackoverflow.com/a/34015469/988941
injectTapEventPlugin();

const { user } = window.__initialProps__;

// default state for search,
// TODO: draw from local storage, save feature?
let location;
if ("geolocation" in navigator) {
    navigator.geolocation.getCurrentPosition(function(position) {
        location = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        }
    });
} else {
  location = {
      lat: 40.7127837,
      lng: 74.0059413,
  }
}
export const initialSearchParams  = {
    verified: true,
    unverified: false,
    purchased: true,
    notPurchased: false,
    capturedTime: true,
    relativeTime: true,
    location,
    address: '',
    radius: 250,
    searchTerm: '',
    users: {},
    assignments:{},
    tags: {},
    loading: false,
    errors: {},
    params: { users: {}, assignments: {}, tags: {} }
}

export const newStory = (id = 1) => ({
     id,
     owner_id: "Bkq1gr2N05OV",
     owner: {
         avatar: null,
         bio: "",
         blocked: false,
         blocking: false,
         created_at: "2017-03-30T21:09:40.944Z",
         disabled: false,
         followed_count: 2,
         following: false,
         following_count: 4,
         full_name: "Revanth",
         id: "Bkq1gr2z05OV",
         location: "",
         object: "user",
         photo_count: 1,
         rating: 0,
         submission_count: 2,
         suspended_until: null,
         trusted: null,
         twitter_handle: null,
         username: "revanth",
         video_count: 1,
     },
     curator_id: "Bkq1gr2N05OV",
     assignment_id: "wOo1PZ9j8Kvl",
     outlet_id: "Z6rg1Vw3Mjkz",
     title: "Piet Mondrian raises from the dead",
     caption: "Now present at the MoMA in new performance piece",
     tags: ["cucu", "freedom", "piet mondrian", "red", "white", "blue"],
     rating: 1,
     created_at: "2017-05-10T21:46:51.000Z",
     highlighted_at: "2017-05-10T21:46:51.000Z",
     posts: [
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         },
         {
             address: "9 S William St, New York, NY",
             assignment_id: "rYd0yDEW8Dp5",
             captured_at: "2017-05-15T16:20:06.000Z",
             created_at: "2017-05-15T16:20:36.507Z",
             curator_id: null,
             duration: null,
             exclusive_to: null,
             exclusive_until: null,
             height: 3024,
             id: "nEZ1lapQ73Lg",
             image: "http://www.piet-mondrian.org/images/paintings/composition-c.jpg",
             is_nsfw: false,
             license: 0,
             location: {
                 coordinates: [ -74.0110538, 40.7038987 ],
                 type: "point"
             },
             object: "post",
             outlet_id: null,
             owner: {
                 avatar: null,
                 bio: "",
                 blocked: false,
                 blocking: false,
                 created_at: "2017-03-30T21:09:40.944Z",
                 disabled: false,
                 followed_count: 2,
                 following: false,
                 following_count: 4,
                 full_name: "Revanth",
                 id: "Bkq1gr2z05OV",
                 location: "",
                 object: "user",
                 photo_count: 1,
                 rating: 0,
                 submission_count: 2,
                 suspended_until: null,
                 trusted: null,
                 twitter_handle: null,
                 username: "revanth",
                 video_count: 1,
             },
             owner_id: "Bkq1gr2z05OV",
             parent: {},
             parent_id: "xYV1RPxJd8Re",
             purchased: false,
             rating: 2,
             status: 2,
             stream: null,
             updated_at: "2017-05-15T16:24:20.008Z",
             video: null,
             width: 4032,
         }
     ]
 })

const stories = () => {
    const theseStories = {};
    for (let x = 0; x < 8; x ++) {
        theseStories[x] = newStory(x);
    }
    return theseStories;
}
let searchParams;
if (localStorage.getItem("searchParams")) {
    searchParams = JSON.parse(localStorage.getItem("searchParams"));
} else {
    searchParams = initialSearchParams;
}

const store = configureStore({ user, searchParams, stories: stories() });
ReactDOM.render(
    <Root store={store}>
        <MuiThemeProvider>
            <Stories />
        </MuiThemeProvider>
    </Root>,
    document.getElementById('app')
);
